{
  "modified": "2025-09-26T09:14:13Z",
  "published": "2025-09-26T09:14:13Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2025-6535"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "libfwupdplugin1"
      }
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "5586ec1437f5a49e92363f7cc77c020def1b25c44226e042a72d9308713d26a4",
        "import_time": "2025-09-26T11:06:10.363507599Z",
        "id": "RLUA-2025-04787",
        "modified_time": "2025-09-26T09:14:13Z"
      }
    ]
  }
}
