{
  "modified": "2025-07-31T19:14:37Z",
  "published": "2025-07-31T19:14:37Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2025-5104",
    "SNYK-PYTHON-COLORAMAPKGSDOW-10305010"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "coloramapkgsdow"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/coloramapkgsdow/MAL-2025-5104.json"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-COLORAMAPKGSDOW-10305010"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "3ea93d109eaee4464d61573448dc1b4e4aa4088dc505603ef31edf7f97d3fb97",
        "import_time": "2025-08-01T10:41:35.027436346Z",
        "id": "RLUA-2025-03568",
        "modified_time": "2025-07-31T19:14:37Z"
      }
    ]
  }
}
