{
  "modified": "2025-08-28T07:11:33Z",
  "published": "2025-08-28T07:11:33Z",
  "schema_version": "1.5.0",
  "id": "",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "py4self",
        "purl": "pkg:pypi/py4self"
      },
      "versions": [
        "1.0.1"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "193a5e5da0b1679d8ba603180e2a081ed084cf5f92f5cad9f92f6d5e076aa7ba",
        "import_time": "2025-08-29T06:41:49.339827282Z",
        "id": "RLMA-2025-04215",
        "modified_time": "2025-08-28T07:11:33Z",
        "versions": [
          "1.0.1"
        ]
      }
    ]
  }
}
